# Generated by Django 5.0.3 on 2024-03-23 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votinghome', '0002_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votinghome.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votinghome.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votinghome.user')),
            ],
            options={
                'unique_together': {('user', 'election')},
            },
        ),
    ]
