# Generated by Django 5.0.3 on 2024-03-23 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votinghome', '0003_user_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votinghome.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votinghome.election')),
            ],
            options={
                'unique_together': {('election', 'candidate')},
            },
        ),
    ]
