# Generated by Django 5.0.3 on 2024-03-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votinghome', '0004_electionresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='election',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='timestamp',
            new_name='voted_at',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='photo',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ElectionResult',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='election',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Election',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
