# Generated by Django 5.0.3 on 2024-03-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votinghome', '0006_remove_vote_voted_at_alter_candidate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.CharField(choices=[('candidate1', 'Candidate 1'), ('candidate2', 'Candidate 2'), ('candidate3', 'Candidate 3')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
