# Generated by Django 5.0.3 on 2024-03-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votinghome', '0007_alter_vote_candidate_delete_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.CharField(max_length=20),
        ),
    ]
