# Generated by Django 5.0.3 on 2024-03-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingcontact', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='timestamp',
        ),
        migrations.DeleteModel(
            name='AdminResponse',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
